#Gradle
org.gradle.jvmargs=-Xmx4G -Dfile.encoding=UTF-8 -Dkotlin.daemon.jvm.options\="-Xmx4G"
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.daemon=true
org.gradle.parallel=true
#Kotlin
kotlin.code.style=official
kotlin.js.compiler=ir
kotlin.js.webpack.major.version=4
kotlin.experimental.tryK2=true
#Android
android.useAndroidX=true
android.nonTransitiveRClass=true
#Compose
org.jetbrains.compose.experimental.jscanvas.enabled=true
org.jetbrains.compose.experimental.macos.enabled=true
compose.desktop.verbose=true
compose.useMavenLocal=false
kotlin.native.ignoreDisabledTargets=true
#KMM
koltin.mpp.androidSourceSetLayoutVersion=2
kotlin.mpp.enableCInteropCommonization=true
kotlin.native.disableCompilerDaemon=true
kotlin.native.useEmbeddableCompilerJar=true
#Kapt
kapt.use.k2=true
kapt.classloaders.cache.size=5
kapt.include.compile.classpath=false
kapt.verbose=true
kapt.use.worker.api=true
xcodeproj=./resources/demo/iosApp
org.gradle.configuration-cache=true